In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,11,12])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a)

[ 1 11 12]


In [5]:
c=np.array([(23,22,1),(2,1,4),(5,6,7)])
print(type(c))

<class 'numpy.ndarray'>


In [6]:
print(c)

[[23 22  1]
 [ 2  1  4]
 [ 5  6  7]]


In [7]:
r=c.ravel()

In [8]:
print(r)

[23 22  1  2  1  4  5  6  7]


In [9]:
zeromatrix=np.zeros((3,3))

In [10]:
print(zeromatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
one=np.ones((2,2))

In [12]:
one

array([[1., 1.],
       [1., 1.]])

In [13]:
ins=np.insert(a,1,10)

In [14]:
ins

array([ 1, 10, 11, 12])

In [15]:
np.append(c,one)

array([23., 22.,  1.,  2.,  1.,  4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.])

In [16]:
txt=np.array([(1,2,3),(2,3,4)])

In [17]:
txt

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
np.concatenate((txt,txt),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])

In [20]:
np.concatenate((txt,txt),axis=None)

array([1, 2, 3, 2, 3, 4, 1, 2, 3, 2, 3, 4])

# Stack

In [21]:
np.hstack((c,c))

array([[23, 22,  1, 23, 22,  1],
       [ 2,  1,  4,  2,  1,  4],
       [ 5,  6,  7,  5,  6,  7]])

In [22]:
np.vstack((a,a))

array([[ 1, 11, 12],
       [ 1, 11, 12]])

In [23]:
#split
np.split(c,3)

[array([[23, 22,  1]]), array([[2, 1, 4]]), array([[5, 6, 7]])]

In [24]:
#Empty
np.empty((2,2))

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [25]:
ran=np.random.random((50,30))

In [26]:
print(ran)

[[0.1980117  0.22468175 0.65517953 ... 0.5032463  0.73407391 0.25459578]
 [0.18382497 0.2284424  0.00474904 ... 0.78998674 0.73525006 0.59212713]
 [0.41891252 0.08038734 0.21785608 ... 0.45909028 0.02986907 0.76054481]
 ...
 [0.85240451 0.29731897 0.7782749  ... 0.46848246 0.3202805  0.25457104]
 [0.6241438  0.67772781 0.51047109 ... 0.09897752 0.48984551 0.31488663]
 [0.26491842 0.397585   0.29737088 ... 0.90730777 0.0756812  0.74785875]]
